spring:
  application:
    name: clean-architecture

  datasource:
    url: jdbc:postgresql://localhost:5432/hanghae_practice
    username: khjin
    password: 0129

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        use_sql_comments: true
        format_sql: true
        show_sql: true

    hibernate:
      ddl-auto: update
    generate-ddl: true
